name: nickurban.com
description: ''

#url: ''
#paginate: 10
permalinks: pretty

markdown: redcarpet
pygments: true

#asset_pipeline:
#  bundle: true
#  compress: true
#  output_path: assets
#  display_path: nil
#  gzip: false

