name: nickurban.com
description: ''

#url: ''
#paginate: 10

pygments: true

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: nil       # Default = nil
  gzip: false             # Default = false

exclude: [Gemfile, Gemfile.lock]
timezone: America/New_York

#markdown: redcarpet
markdown: rdiscount
rdiscount:
  extensions: [smart, autolink]

permalink: '/blog/:categories/:title/'
category_dir: 'blog'
category_title_prefix: ''

