name: nickurban.com
description: ''

#url: ''
#paginate: 10

pygments: true

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: nil       # Default = nil
  gzip: false             # Default = false

exclude: [Gemfile, Gemfile.lock, Rakefile]
timezone: America/New_York

#markdown: redcarpet
markdown: rdiscount
rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants

#permalink: '/blog/:categories/:title/'
permalink: '/blog/:title/'
category_dir: 'blog/categories'
category_title_prefix: ''

